#!/bin/bash

enable_classicextensions () {
    cd "/home/${NB_USER}"
    # community extensions
    jupyter contrib nbextension install --sys-prefix
    # widgets
    jupyter nbextension enable --py widgetsnbextension --sys-prefix
}

install_jupyter_server_proxy () {
    jupyter serverextension enable --sys-prefix --py jupyter_server_proxy
    jupyter labextension install @jupyterlab/server-proxy@^2.1.1
    jupyter lab build -y
    jupyter lab clean -y
    npm cache clean --force
    rm -rf "${HOME}/.cache/yarn"
    rm -rf "${HOME}/.node-gyp"
    fix-permissions "${CONDA_DIR}"
    fix-permissions "${HOME}"
}

cleanup () {
    # clean lab extensions and npm files
    jupyter lab clean -y
    conda clean --all -y
}

main () {
    enable_classicextensions
    install_jupyter_server_proxy
    cleanup
}
