# Re-tag staging SHA-tagged image with git tag and 'latest'
# tags can be anything, but typically calver string (2020.06.10)
name: Publish
on:
  push:
    tags:
    - '*'

env:
  DOCKER_ORG: illumidesk
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [flatiron-base, flatiron-notebook, flatiron-grader]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Job Environment Variables
      run: |
        SHA7="${GITHUB_SHA::7}"
        TAG="${GITHUB_REF##*/}"
        echo "::set-env name=SHA7::${SHA7}"
        echo "::set-env name=TAG::${TAG}"

    - name: Pull Image for Corresponding GitHub Commit
      run: |
        docker pull ${DOCKER_ORG}/${{ matrix.IMAGE }}:${SHA7}

    - name: Authenticate with DockerHub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: Retag and Push Image
      run: |
        docker tag ${DOCKER_ORG}/${{ matrix.IMAGE }}:${SHA7} ${DOCKER_ORG}/${{ matrix.IMAGE }}:latest
        docker tag ${DOCKER_ORG}/${{ matrix.IMAGE }}:${SHA7} ${DOCKER_ORG}/${{ matrix.IMAGE }}:${TAG}
        docker push ${DOCKER_ORG}/${{ matrix.IMAGE }}:latest
        docker push ${DOCKER_ORG}/${{ matrix.IMAGE }}:${TAG}
